#!/usr/bin/env python3
"""Generate domain tripwires for BOTH Claude Code and GitHub Copilot from one manifest.

A tripwire is a small instruction file that fires when you touch a domain, and
whose whole job is to put that domain's traps in front of you BEFORE you act.

⭐ WHY GENERATED, NOT HANDWRITTEN

Two assistants, two formats, same content:

    Claude Code   .claude/skills/<name>/SKILL.md          fires on description match
    Copilot       .github/instructions/<name>.instructions.md   fires on applyTo glob

Handwriting both guarantees they fork - one gets a fix, the other keeps the old
rule, and the stale one is trusted because it looks maintained. Generating both
from the manifest below makes forking structurally impossible. Regenerate after
editing DOMAINS; never edit the outputs.

⭐ WHY THIS MATTERS

Different assistants are approved at different organisations. The durable,
portable asset is therefore the plain-markdown knowledge layer plus `traps.py` -
both of which any assistant can read and run. This script is what keeps a
tool-specific accelerant from becoming the only place the knowledge lives.

⚠️ Tripwire bodies deliberately stay THIN: the pointer, the command, and only
those rules that must be obeyed before reading anything else. Everything else is
loaded on demand by `traps.py`. A fat tripwire is a second copy of the docs, and
copies rot.

Usage:
    python scripts/tripwires.py            # write both formats
    python scripts/tripwires.py --check    # verify outputs match the manifest
"""
from __future__ import annotations

import argparse
import io
import json
import os
import subprocess
import sys

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, OSError):
        pass

# ---------------------------------------------------------------------------
# THE MANIFEST. One entry per hazardous domain.
#
# The cap is deliberate: at most 8 tripwires. Adding a ninth means merging or
# evicting one, because descriptions are always-loaded budget and a diluted
# trigger set fires on nothing.
# ---------------------------------------------------------------------------
HERE = os.path.dirname(os.path.abspath(__file__))

CAP = 8

DOMAINS = [
    # ⚠️ EXAMPLE ONLY - REPLACE. These two show the shape; they assert nothing
    # about your system, because a starter pack that does is wrong on day one
    # and trusted anyway. Real profiles live in `profiles/`; load one with
    # `--profile profiles/devops.py`, then edit it as incidents earn real rules.
    {
        "name": "database",
        "traps_scope": "migrations",
        "when": "writing migrations or changing the schema",
        "apply_to": "**/migrations/**,**/schema.sql",
        "rules": [
            "**How long does this lock the table at production row counts?** "
            "An ALTER that is instant locally can hold a lock for minutes.",
            "**Is the rollback real?** Many `down()` methods exist to satisfy "
            "the framework and would not actually restore anything.",
        ],
    },
    {
        "name": "deploy",
        "traps_scope": "deploy",
        "when": "changing deployment configuration, CI, or anything that ships to production",
        "apply_to": "deploy/**,.github/workflows/**,**/Dockerfile*",
        "rules": [
            "**Which push actually deploys?** The most expensive surprise in CI "
            "is a job you did not know was a deploy.",
            "**Is this safe to roll back?** If not, it is a DECISIONS.md entry, "
            "not just a commit.",
        ],
    },
]

# ---------------------------------------------------------------------------
# ⭐ ONE IMPLEMENTATION, MANY REPOS. If `scripts/kernel_config.py` exists beside
# this file, any constant it defines overrides the EXAMPLE values above.
#
# This exists because the alternative was caught happening: two copies of these
# scripts, one with a fix and one without, drifting 50-plus lines apart - the
# exact duplication-divergence failure this project tells you to design out.
# Code is identical everywhere; only configuration differs, and configuration
# lives in a file that is obviously configuration.
# ---------------------------------------------------------------------------
try:
    import kernel_config as _cfg                      # noqa: E402
except Exception:
    try:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        import kernel_config as _cfg                  # noqa: E402
    except Exception:
        _cfg = None
if _cfg is not None:
    for _k in dir(_cfg):
        if _k.isupper():
            globals()[_k] = getattr(_cfg, _k)

CLAUDE_DIR = ".claude/skills"
COPILOT_DIR = ".github/instructions"

BANNER = ("<!-- GENERATED by scripts/tripwires.py from its DOMAINS manifest. "
          "Do not edit; edit the manifest and regenerate. -->")


def auto_domains(root, cap):
    """Build the manifest from the repo's OWN trap distribution. Nothing invented.

    ⭐ This exists because install refused to generate tripwires at all, on the
    grounds that the shipped manifest is EXAMPLE domains and seeding those is
    wallpaper. True - and a false choice. `traps.py --domains` already knows
    which directories this repo's surprises actually live in. Deriving the
    triggers from that is automatic AND real.

    ⚠️ The RULES stay empty. A trigger says "load this domain's traps before you
    act", which is a fact about where the traps are. A rule says "never do X
    here", which a repo earns one incident at a time. Generating the first is
    retrieval; generating the second would be the wallpaper.
    """
    r = subprocess.run([sys.executable, os.path.join(HERE, "traps.py"),
                        "--json"], cwd=root, capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    try:
        hits = json.loads(r.stdout or "{}").get("hits", [])
    except Exception:
        return []

    weight = {}
    for h in hits:
        if h.get("kind") == "trap":
            weight[h.get("domain", "")] = weight.get(h.get("domain", ""), 0) + 1
    # ⚠️ `root` is the top-level bucket, not a directory - it cannot be an
    # applyTo glob, and a tripwire that matches everything fires on nothing.
    ranked = [(d, n) for d, n in weight.items()
              if d and d != "root" and not d.startswith(".") and n >= 3]
    ranked.sort(key=lambda kv: -kv[1])

    out = []
    for d, n in ranked[:cap]:
        out.append({
            "name": d.replace("/", "-").replace("_", "-").lower(),
            "traps_scope": d,
            "when": "working anywhere under %s/ (%d traps recorded there)" % (d, n),
            "apply_to": "%s/**" % d,
            # No rules. See the docstring: triggers are derived, rules are earned.
            "rules": [],
        })
    return out


def body(d: dict) -> str:
    rules = "\n".join(f"- {r}" for r in d["rules"])
    return f"""{BANNER}

# {d['name']}

⚠️ **Before acting, load this domain's traps:**

```bash
python scripts/traps.py {d['traps_scope']}
```

That command is the point of this file. Traps are recorded in situ under a
`⚠️` marker, scoped so you load only the domain you are touching. The rules
below are ONLY those that must be obeyed *before* you have read anything else.

{rules}

See `AGENTS.md` for the machine map, the operating rules and the domain index.
"""


def claude_skill(d: dict) -> tuple[str, str]:
    fm = (f"---\nname: {d['name']}\n"
          f"description: Use when {d['when']}.\n---\n\n")
    return os.path.join(CLAUDE_DIR, d["name"], "SKILL.md"), fm + body(d)


def copilot_instruction(d: dict) -> tuple[str, str]:
    # Copilot's path-scoped instructions: applyTo takes comma-separated globs.
    fm = f"---\napplyTo: \"{d['apply_to']}\"\n---\n\n"
    return os.path.join(COPILOT_DIR, f"{d['name']}.instructions.md"), fm + body(d)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify outputs match the manifest; non-zero if stale")
    ap.add_argument("--auto", action="store_true",
                    help="derive the manifest from this repo's own trap "
                         "distribution instead of the example domains")
    ap.add_argument("--profile",
                    help="load DOMAINS from a profile file, e.g. profiles/devops.py. "
                         "Starter profiles ship QUESTIONS, not claims about your "
                         "system - replace them as incidents earn real rules.")
    args = ap.parse_args()

    global DOMAINS
    if args.auto:
        derived = auto_domains(os.getcwd(), CAP)
        if not derived:
            print("  --auto found no domain with 3+ traps yet.")
            print("  That is normal in a young repo: write markers as you work,")
            print("  then re-run. Generating triggers for empty domains would be")
            print("  the wallpaper this tool refuses to produce.")
            return 0
        DOMAINS = derived
        print("  --auto: %d domain(s) derived from this repo's own traps"
              % len(DOMAINS))
    if args.profile:
        # Executed rather than imported so a profile can live anywhere, and so the
        # file stays readable as data by a human deciding whether to trust it.
        ns = {}
        src = io.open(args.profile, encoding="utf-8").read()
        exec(compile(src, args.profile, "exec"), ns)
        if "DOMAINS" not in ns:
            print("ERROR: %s defines no DOMAINS list" % args.profile)
            return 1
        DOMAINS = ns["DOMAINS"]
        print("profile: %s (%d domains)" % (args.profile, len(DOMAINS)))

    if len(DOMAINS) > CAP:
        print(f"ERROR: {len(DOMAINS)} tripwires exceeds the cap of {CAP}. "
              "Merge or evict one - a diluted trigger set fires on nothing.")
        return 1

    # ⚠️ NEVER-GENERATED IS NOT STALE, and conflating them made a fresh install
    # fail CI on its first push over files it had never been given. `install`
    # deliberately does not run this - seeding a repo with the EXAMPLE domains
    # would be exactly the wallpaper this project warns about - so "no outputs
    # at all" means tripwires are not adopted yet, which is a legitimate state.
    # The moment ONE output exists, they must all match: a half-generated set is
    # the fork this file exists to prevent.
    any_output = any(os.path.exists(p) for d in DOMAINS
                     for p, _t in (claude_skill(d), copilot_instruction(d)))

    stale = []
    for d in DOMAINS:
        for path, text in (claude_skill(d), copilot_instruction(d)):
            existing = None
            if os.path.exists(path):
                existing = io.open(path, encoding="utf-8").read()
            if existing == text:
                continue
            if args.check:
                if any_output:
                    stale.append(path)
                continue
            os.makedirs(os.path.dirname(path), exist_ok=True)
            io.open(path, "w", encoding="utf-8", newline="\n").write(text)
            print(f"  wrote {path}")

    # --- compile opt-in traps into interlocks -------------------------------
    # ⭐ Generated from the SAME markers as everything else, so a blocking rule
    # cannot drift from the trap that justifies it. The rules land in a committed
    # JSON file rather than living in the guard, because a human must be able to
    # read every rule that can stop their work, and delete one they disagree with.
    blocks_path = os.path.join(".claude", "agent-root-blocks.json")
    blocks_text = None
    try:
        import json as _json
        import subprocess as _sp
        r = _sp.run([sys.executable, os.path.join(HERE, "traps.py"), "--json"],
                    capture_output=True, text=True, encoding="utf-8",
                    errors="replace")
        data = _json.loads(r.stdout or "{}")
        blocks = data.get("blocks", [])
        blocks_text = _json.dumps(
            {"note": ("Generated by tripwires.py from <!-- block: ... --> "
                      "directives in the repo's own traps. Edit a trap, not this "
                      "file. Delete a rule here to disable it until regenerated."),
             "blocks": blocks},
            indent=2, ensure_ascii=False) + "\n"
    except Exception as e:                                       # noqa: BLE001
        # ⚠️ Never fail the whole generator because the block compiler tripped.
        print("  (blocks not compiled: %s)" % type(e).__name__)

    if blocks_text is not None:
        existing = (io.open(blocks_path, encoding="utf-8").read()
                    if os.path.exists(blocks_path) else None)
        # ⚠️ NO RULES AND NO FILE IS A CONSISTENT STATE, NOT A STALE ONE. The
        # first version demanded the file unconditionally, so a repo that had
        # declared zero interlocks - which is every repo on the day it installs
        # this - failed CI on its first push, before the user had done anything
        # wrong. A check that fails on a correct state trains people to ignore
        # it, and the guard is the first thing they then switch off.
        #
        # The asymmetry is deliberate: rules DECLARED but not compiled must
        # still fail loudly, because an interlock nobody compiled is an
        # interlock nobody is enforcing.
        if not blocks and existing is None:
            pass
        elif existing != blocks_text:
            if args.check:
                stale.append(blocks_path)
            else:
                os.makedirs(os.path.dirname(blocks_path), exist_ok=True)
                io.open(blocks_path, "w", encoding="utf-8",
                        newline="\n").write(blocks_text)
                n = blocks_text.count('"on":')
                print("  wrote %s (%d interlock%s)"
                      % (blocks_path, n, "" if n == 1 else "s"))

    if args.check:
        if stale:
            print("STALE (regenerate):")
            for p in stale:
                print(f"  {p}")
            return 1
        print(f"all {len(DOMAINS) * 2} tripwire files match the manifest")
    else:
        print(f"\n{len(DOMAINS)} domains -> {len(DOMAINS) * 2} files "
              f"(Claude skills + Copilot instructions), cap {CAP}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
