#!/usr/bin/env python3
"""Generate domain tripwires for BOTH Claude Code and GitHub Copilot from one manifest.

A tripwire is a small instruction file that fires when you touch a domain, and
whose whole job is to put that domain's traps in front of you BEFORE you act.

⭐ WHY GENERATED, NOT HANDWRITTEN

Two assistants, two formats, same content:

    Claude Code   .claude/skills/<name>/SKILL.md          fires on description match
    Copilot       .github/instructions/<name>.instructions.md   fires on applyTo glob

Handwriting both guarantees they fork - one gets a fix, the other keeps the old
rule, and the stale one is trusted because it looks maintained. Generating both
from the manifest below makes forking structurally impossible. Regenerate after
editing DOMAINS; never edit the outputs.

⭐ WHY THIS MATTERS

Different assistants are approved at different organisations. The durable,
portable asset is therefore the plain-markdown knowledge layer plus `traps.py` -
both of which any assistant can read and run. This script is what keeps a
tool-specific accelerant from becoming the only place the knowledge lives.

⚠️ Tripwire bodies deliberately stay THIN: the pointer, the command, and only
those rules that must be obeyed before reading anything else. Everything else is
loaded on demand by `traps.py`. A fat tripwire is a second copy of the docs, and
copies rot.

Usage:
    python scripts/tripwires.py            # write both formats
    python scripts/tripwires.py --check    # verify outputs match the manifest
"""
from __future__ import annotations

import argparse
import io
import os
import sys

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, OSError):
        pass

# ---------------------------------------------------------------------------
# THE MANIFEST. One entry per hazardous domain.
#
# The cap is deliberate: at most 8 tripwires. Adding a ninth means merging or
# evicting one, because descriptions are always-loaded budget and a diluted
# trigger set fires on nothing.
# ---------------------------------------------------------------------------
CAP = 8

DOMAINS = [
    # ⚠️ EXAMPLE ONLY - REPLACE. These two show the shape; they assert nothing
    # about your system, because a starter pack that does is wrong on day one
    # and trusted anyway. Real profiles live in `profiles/`; load one with
    # `--profile profiles/devops.py`, then edit it as incidents earn real rules.
    {
        "name": "database",
        "traps_scope": "migrations",
        "when": "writing migrations or changing the schema",
        "apply_to": "**/migrations/**,**/schema.sql",
        "rules": [
            "**How long does this lock the table at production row counts?** "
            "An ALTER that is instant locally can hold a lock for minutes.",
            "**Is the rollback real?** Many `down()` methods exist to satisfy "
            "the framework and would not actually restore anything.",
        ],
    },
    {
        "name": "deploy",
        "traps_scope": "deploy",
        "when": "changing deployment configuration, CI, or anything that ships to production",
        "apply_to": "deploy/**,.github/workflows/**,**/Dockerfile*",
        "rules": [
            "**Which push actually deploys?** The most expensive surprise in CI "
            "is a job you did not know was a deploy.",
            "**Is this safe to roll back?** If not, it is a DECISIONS.md entry, "
            "not just a commit.",
        ],
    },
]

# ---------------------------------------------------------------------------
# ⭐ ONE IMPLEMENTATION, MANY REPOS. If `scripts/kernel_config.py` exists beside
# this file, any constant it defines overrides the EXAMPLE values above.
#
# This exists because the alternative was caught happening: two copies of these
# scripts, one with a fix and one without, drifting 50-plus lines apart - the
# exact duplication-divergence failure this project tells you to design out.
# Code is identical everywhere; only configuration differs, and configuration
# lives in a file that is obviously configuration.
# ---------------------------------------------------------------------------
try:
    import kernel_config as _cfg                      # noqa: E402
except Exception:
    try:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        import kernel_config as _cfg                  # noqa: E402
    except Exception:
        _cfg = None
if _cfg is not None:
    for _k in dir(_cfg):
        if _k.isupper():
            globals()[_k] = getattr(_cfg, _k)

CLAUDE_DIR = ".claude/skills"
COPILOT_DIR = ".github/instructions"

BANNER = ("<!-- GENERATED by scripts/tripwires.py from its DOMAINS manifest. "
          "Do not edit; edit the manifest and regenerate. -->")


def body(d: dict) -> str:
    rules = "\n".join(f"- {r}" for r in d["rules"])
    return f"""{BANNER}

# {d['name']}

⚠️ **Before acting, load this domain's traps:**

```bash
python scripts/traps.py {d['traps_scope']}
```

That command is the point of this file. Traps are recorded in situ under a
`⚠️` marker, scoped so you load only the domain you are touching. The rules
below are ONLY those that must be obeyed *before* you have read anything else.

{rules}

See `AGENTS.md` for the machine map, the operating rules and the domain index.
"""


def claude_skill(d: dict) -> tuple[str, str]:
    fm = (f"---\nname: {d['name']}\n"
          f"description: Use when {d['when']}.\n---\n\n")
    return os.path.join(CLAUDE_DIR, d["name"], "SKILL.md"), fm + body(d)


def copilot_instruction(d: dict) -> tuple[str, str]:
    # Copilot's path-scoped instructions: applyTo takes comma-separated globs.
    fm = f"---\napplyTo: \"{d['apply_to']}\"\n---\n\n"
    return os.path.join(COPILOT_DIR, f"{d['name']}.instructions.md"), fm + body(d)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify outputs match the manifest; non-zero if stale")
    ap.add_argument("--profile",
                    help="load DOMAINS from a profile file, e.g. profiles/devops.py. "
                         "Starter profiles ship QUESTIONS, not claims about your "
                         "system - replace them as incidents earn real rules.")
    args = ap.parse_args()

    global DOMAINS
    if args.profile:
        # Executed rather than imported so a profile can live anywhere, and so the
        # file stays readable as data by a human deciding whether to trust it.
        ns = {}
        src = io.open(args.profile, encoding="utf-8").read()
        exec(compile(src, args.profile, "exec"), ns)
        if "DOMAINS" not in ns:
            print("ERROR: %s defines no DOMAINS list" % args.profile)
            return 1
        DOMAINS = ns["DOMAINS"]
        print("profile: %s (%d domains)" % (args.profile, len(DOMAINS)))

    if len(DOMAINS) > CAP:
        print(f"ERROR: {len(DOMAINS)} tripwires exceeds the cap of {CAP}. "
              "Merge or evict one - a diluted trigger set fires on nothing.")
        return 1

    stale = []
    for d in DOMAINS:
        for path, text in (claude_skill(d), copilot_instruction(d)):
            existing = None
            if os.path.exists(path):
                existing = io.open(path, encoding="utf-8").read()
            if existing == text:
                continue
            if args.check:
                stale.append(path)
                continue
            os.makedirs(os.path.dirname(path), exist_ok=True)
            io.open(path, "w", encoding="utf-8", newline="\n").write(text)
            print(f"  wrote {path}")

    if args.check:
        if stale:
            print("STALE (regenerate):")
            for p in stale:
                print(f"  {p}")
            return 1
        print(f"all {len(DOMAINS) * 2} tripwire files match the manifest")
    else:
        print(f"\n{len(DOMAINS)} domains -> {len(DOMAINS) * 2} files "
              f"(Claude skills + Copilot instructions), cap {CAP}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
